---
- name: Install Metricbeat
  hosts: webservers
  become: true
  tasks:
  - name: download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Install metricbeat
    command: sudo dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/roles/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module for metricbeat
    command: metricbeat modules enable docker
  - name: Run metricbeat setup
    command: metricbeat setup
  - name: Run service metricbeat start
    command: service metricbeat start
  - name: enable metricbeat
    systemd:
      name: metricbeat
      state: started
      enabled: yes
